const Message = {
    // controllers
    AUTH_CONTROLLER: 'AuthController ',
    USER_CONTROLLER: 'UserController ',
    AI_CONTROLLER: 'AIController ',
    CONTACT_CONTROLLER:'ContactController ',
    LIST_CONTROLLER:'ListController ',

    USER_NOT_FOUND: 'User not found ',
    INVALID_CREDENTIALS: 'Invalid credentials ',
    SERVER_ERROR: 'Server error ',
    VALIDATION_ERROR: 'Validation error ',
    USER_CREATED: 'User created successfully ',
    AI_SEARCH_ATTEMPT: 'AI Search Attempt',
    LOGIN_SUCCESS: 'Login successful ',
    USER_FOUND: 'User found successfully ',
    FAILED_TO_AUTHENTICATE: 'Failed to authenticate token ',
    NO_TOKEN_PROVIDED: 'No token provided ',
    LOG_START: 'LOG_START ',
    LOG_END: 'LOG_END ',
    LOGIN_ATTEMPT: 'Login attempt ',
    REGISTRATION_ATTEMPT: 'Registration attempt ',
    FETCHING_USER_INFO: 'Fetching user info ',
    ERROR_IN: 'Error In ',
    SUCCESS: 'Success ',
    EMPTY_FIELD: 'Field cannot be empty ',
    MONGODB_CONNECTION_ERROR: 'MongoDB connection error ',
    MONGODB_CONNECTED: 'MongoDB connected ',
    EMAIL_ALREADY_EXISTS: 'Email already exists ',
    ID_IS_REQUIRED: 'ID is required ',
    DELETE_USER_ATTEMPT: 'Delete User Attempt',
    UPDATE_USER_ATTEMPT: 'Update User Attempt',
    USER_DELETED: 'User deleted successfully ',
    USER_UPDATED: 'User updated successfully ',
    GET_ALL_USERS_ATTEMPT: 'Get All Users Attempt',
    ADMIN_ONLY: 'Admin access required ',
    QUERY_REQUIRED: 'Query is required ',
    AI_SEARCH: 'AI search ',

    // common curd operations
    DATA_FOUND: 'Data found successfully ',
    DATA_NOT_FOUND:'Data not found ',
    CREATE_ATTEMPT: 'Create attempt ',
    FETCHING_RECORD: 'Fetching record ',
    DELETE_RECORD_ATTEMPT: 'Delete Record Attempt ',
    UPDATE_RECORD_ATTEMPT:'Update Record Attempt ',
    RECORD_UPDATED:'Record updated successfully ',
    GET_ALL_RECORD_ATTEMPT: 'Get All Records Attempt ',
    DUPLICATE_RECORD: 'Record Already exist ',
    RECODE_CREATED: 'Record created successfully',
    UPLOAD_FILE: 'Upload File ',
    IS_REQUIRED: 'is required ',
    UPLOADED_CONTACT_SUCCESS: 'Upload Contact successfully',
    ADD_LIST_CONTACTS:'Add List Contacts '
};
module.exports = Message;